name: RoseSkyblock
version: '@version@'
authors: [Esophose]
main: dev.rosewood.roseskyblock.RoseSkyblock
api-version: '1.13'
softdepend: [WorldEdit, PlaceholderAPI]
commands:
  skyblock:
    aliases: [rsb, roseskyblock]
    description: The base RoseSkyblock command.
